name: Publish evidence item
permissions:
  id-token: write
  contents: read
on:
  push:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Step-1
        run: echo "hello from step 1"
        
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Publish Evidence Action
        # uses: cloudbees-gha-cbp/publish-evidence-item@test
        uses: akashsami4456/gha-action@main
        id: go-action
        with :
          cloudbees-url: "https://api.saas-preprod.beescloud.com/"
          # cloudbees-url: "https://api.cloudbees.io"
          content: "Test Pre-Prod"
